export const STATUS_VOTE = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
}

export const VOTE_TYPE = {
  MULTIPLE_CHOICE: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  SHORT_ANSWER: 'SHORT_ANSWER',
}
